import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Built with Syra",
  description: "Generated by Syra, the AI website builder.",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
