export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  image: string;
  description: string;
  specs: {
    display: string;
    processor: string;
    ram: string;
    storage: string;
    camera: string;
    battery: string;
  };
}

export const products: Product[] = [
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "flagship",
    price: 1199.99,
    image: "/images/products/iphone-15-pro-max.webp",
    description: "The ultimate iPhone experience. Featuring the A17 Bionic chip, a pro camera system, and a durable titanium design.",
    specs: {
      display: "6.7-inch Super Retina XDR display with ProMotion",
      processor: "A17 Bionic chip",
      ram: "8GB",
      storage: "256GB, 512GB, 1TB",
      camera: "48MP Main, 12MP Ultra Wide, 12MP Telephoto",
      battery: "Up to 29 hours video playback",
    },
  },
  {
    id: "samsung-galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "flagship",
    price: 1299.99,
    image: "/images/products/samsung-galaxy-s24-ultra.webp",
    description: "Unleash epic with Galaxy AI. The most advanced Galaxy Ultra yet, with an incredible camera and S Pen.",
    specs: {
      display: "6.8-inch Dynamic AMOLED 2X, 120Hz",
      processor: "Snapdragon 8 Gen 3 for Galaxy",
      ram: "12GB",
      storage: "256GB, 512GB, 1TB",
      camera: "200MP Wide, 12MP Ultra Wide, 10MP Telephoto (3x), 50MP Telephoto (5x)",
      battery: "5000 mAh",
    },
  },
  {
    id: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro",
    brand: "Google",
    category: "flagship",
    price: 999.00,
    image: "/images/products/google-pixel-8-pro.webp",
    description: "The most advanced Pixel camera ever, with Google AI for smarter photos and videos.",
    specs: {
      display: "6.7-inch Super Actua display, 120Hz",
      processor: "Google Tensor G3",
      ram: "12GB",
      storage: "128GB, 256GB, 512GB",
      camera: "50MP Wide, 48MP Ultra Wide, 48MP Telephoto",
      battery: "5050 mAh",
    },
  },
  {
    id: "oneplus-12",
    name: "OnePlus 12",
    brand: "OnePlus",
    category: "flagship",
    price: 799.00,
    image: "/images/products/oneplus-12.webp",
    description: "Smooth beyond belief. Flagship power with a stunning display and fast charging.",
    specs: {
      display: "6.82-inch Fluid AMOLED, 120Hz",
      processor: "Snapdragon 8 Gen 3",
      ram: "12GB, 16GB",
      storage: "256GB, 512GB",
      camera: "50MP Main, 48MP Ultra Wide, 64MP Periscope Telephoto",
      battery: "5400 mAh",
    },
  },
  {
    id: "xiaomi-14-ultra",
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    category: "flagship",
    price: 1099.00,
    image: "/images/products/xiaomi-14-ultra.webp",
    description: "Master photography with Leica optics. A professional imaging powerhouse.",
    specs: {
      display: "6.73-inch AMOLED, 120Hz",
      processor: "Snapdragon 8 Gen 3",
      ram: "12GB, 16GB",
      storage: "256GB, 512GB, 1TB",
      camera: "50MP Main (1-inch sensor), 50MP Ultra Wide, 50MP Telephoto (3.2x), 50MP Periscope Telephoto (5x)",
      battery: "5000 mAh",
    },
  },
  {
    id: "samsung-galaxy-a54",
    name: "Samsung Galaxy A54",
    brand: "Samsung",
    category: "budget",
    price: 449.00,
    image: "/images/products/samsung-galaxy-a54.webp",
    description: "Awesome camera, awesome screen, awesome battery life. Great value for money.",
    specs: {
      display: "6.4-inch Super AMOLED, 120Hz",
      processor: "Exynos 1380",
      ram: "6GB, 8GB",
      storage: "128GB, 256GB",
      camera: "50MP Main, 12MP Ultra Wide, 5MP Macro",
      battery: "5000 mAh",
    },
  },
  {
    id: "google-pixel-7a",
    name: "Google Pixel 7a",
    brand: "Google",
    category: "budget",
    price: 499.00,
    image: "/images/products/google-pixel-7a.webp",
    description: "Google Tensor G2 chip makes Pixel 7a fast and secure, with amazing camera features.",
    specs: {
      display: "6.1-inch OLED, 90Hz",
      processor: "Google Tensor G2",
      ram: "8GB",
      storage: "128GB",
      camera: "64MP Wide, 13MP Ultra Wide",
      battery: "4385 mAh",
    },
  },
  {
    id: "redmi-note-13-pro-plus",
    name: "Redmi Note 13 Pro+",
    brand: "Xiaomi",
    category: "budget",
    price: 399.00,
    image: "/images/products/redmi-note-13-pro-plus.webp",
    description: "200MP camera with OIS, IP68 dust and water resistance, and 120W HyperCharge.",
    specs: {
      display: "6.67-inch AMOLED, 120Hz",
      processor: "MediaTek Dimensity 7200 Ultra",
      ram: "8GB, 12GB",
      storage: "256GB, 512GB",
      camera: "200MP Main, 8MP Ultra Wide, 2MP Macro",
      battery: "5000 mAh",
    },
  },
  {
    id: "nothing-phone-2a",
    name: "Nothing Phone (2a)",
    brand: "Nothing",
    category: "budget",
    price: 349.00,
    image: "/images/products/nothing-phone-2a.webp",
    description: "Fresh design, powerful performance, and a unique Glyph Interface.",
    specs: {
      display: "6.7-inch AMOLED, 120Hz",
      processor: "MediaTek Dimensity 7200 Pro",
      ram: "8GB, 12GB",
      storage: "128GB, 256GB",
      camera: "50MP Main, 50MP Ultra Wide",
      battery: "5000 mAh",
    },
  },
  {
    id: "asus-rog-phone-8-pro",
    name: "ASUS ROG Phone 8 Pro",
    brand: "ASUS",
    category: "gaming",
    price: 1199.00,
    image: "/images/products/asus-rog-phone-8-pro.webp",
    description: "The ultimate gaming phone. Unrivaled performance, advanced cooling, and customizable controls.",
    specs: {
      display: "6.78-inch AMOLED, 165Hz",
      processor: "Snapdragon 8 Gen 3",
      ram: "16GB, 24GB",
      storage: "512GB, 1TB",
      camera: "50MP Main, 13MP Ultra Wide, 32MP Telephoto",
      battery: "5500 mAh",
    },
  },
  {
    id: "redmagic-9-pro",
    name: "RedMagic 9 Pro",
    brand: "RedMagic",
    category: "gaming",
    price: 649.00,
    image: "/images/products/redmagic-9-pro.webp",
    description: "True full-screen gaming with a powerful cooling system and shoulder triggers.",
    specs: {
      display: "6.8-inch AMOLED, 120Hz",
      processor: "Snapdragon 8 Gen 3",
      ram: "12GB, 16GB",
      storage: "256GB, 512GB",
      camera: "50MP Main, 8MP Ultra Wide, 2MP Macro",
      battery: "6500 mAh",
    },
  },
  {
    id: "lenovo-legion-y70",
    name: "Lenovo Legion Y70",
    brand: "Lenovo",
    category: "gaming",
    price: 499.00,
    image: "/images/products/lenovo-legion-y70.webp",
    description: "Sleek design with high-performance gaming capabilities at an attractive price.",
    specs: {
      display: "6.67-inch OLED, 144Hz",
      processor: "Snapdragon 8+ Gen 1",
      ram: "8GB, 12GB, 16GB",
      storage: "128GB, 256GB, 512GB",
      camera: "50MP Main, 13MP Ultra Wide, 2MP Depth",
      battery: "5100 mAh",
    },
  },
  {
    id: "sony-xperia-1-v",
    name: "Sony Xperia 1 V",
    brand: "Sony",
    category: "camera",
    price: 1399.99,
    image: "/images/products/sony-xperia-1-v.webp",
    description: "Professional imaging and videography in your pocket. True optical zoom and 4K HDR display.",
    specs: {
      display: "6.5-inch 4K HDR OLED, 120Hz",
      processor: "Snapdragon 8 Gen 2",
      ram: "12GB",
      storage: "256GB, 512GB",
      camera: "48MP Main, 12MP Ultra Wide, 12MP Telephoto (3.5x-5.2x optical zoom)",
      battery: "5000 mAh",
    },
  },
  {
    id: "vivo-x100-pro",
    name: "Vivo X100 Pro",
    brand: "Vivo",
    category: "camera",
    price: 999.00,
    image: "/images/products/vivo-x100-pro.webp",
    description: "Co-engineered with ZEISS. Exceptional low-light photography and stunning portraits.",
    specs: {
      display: "6.78-inch LTPO AMOLED, 120Hz",
      processor: "MediaTek Dimensity 9300",
      ram: "12GB, 16GB",
      storage: "256GB, 512GB, 1TB",
      camera: "50MP Main (1-inch sensor), 50MP Ultra Wide, 50MP Periscope Telephoto (4.3x optical zoom)",
      battery: "5400 mAh",
    },
  },
  {
    id: "oppo-find-x7-ultra",
    name: "Oppo Find X7 Ultra",
    brand: "Oppo",
    category: "camera",
    price: 1099.00,
    image: "/images/products/oppo-find-x7-ultra.webp",
    description: "Quad camera system with dual periscope lenses. The new benchmark for mobile imaging.",
    specs: {
      display: "6.82-inch LTPO AMOLED, 120Hz",
      processor: "Snapdragon 8 Gen 3",
      ram: "12GB, 16GB",
      storage: "256GB, 512GB",
      camera: "50MP Main (1-inch sensor), 50MP Ultra Wide, 50MP Periscope Telephoto (2.8x), 50MP Periscope Telephoto (6x)",
      battery: "5000 mAh",
    },
  },
];
