/**
 * Represents the current state of the player's game.
 */
export interface GameState {
  score: number; // Current number of cookies available to spend
  totalCookies: number; // All-time cookies earned (for achievements/leaderboard)
  clicks: number; // Total number of times the cookie was clicked
  lastClickAt: number; // Timestamp of the last click
  upgrades: Record<string, number>; // Dictionary mapping Upgrade IDs to the quantity owned
  startTime: number; // Timestamp of when the current run started
}

/**
 * Represents a purchasable upgrade in the shop.
 */
export interface Upgrade {
  id: string;
  name: string;
  description: string;
  baseCost: number;
  costMultiplier: number; // How much the cost increases per purchase (e.g., 1.15)
  cps: number; // Cookies Per Second generated by one instance of this upgrade
  cpc: number; // Cookies Per Click added by one instance of this upgrade
  icon: string; // Emoji or URL for the upgrade icon
}

/**
 * Represents the user's profile and persisted data.
 */
export interface UserData {
  userId: string;
  username: string;
  gameState: GameState;
  lastSavedAt: number;
}

/**
 * Configuration for the site/game.
 */
export interface SiteConfig {
  name: string;
  description: string;
  version: string;
}

/**
 * Navigation item for the header/menu.
 */
export interface NavItem {
  label: string;
  href: string;
  icon?: string;
}

/**
 * Props for the main Clicker component.
 */
export interface ClickerProps {
  gameState: GameState;
  onCookieClick: () => void;
  currentCps: number;
}

/**
 * Props for the Shop component.
 */
export interface ShopProps {
  gameState: GameState;
  availableUpgrades: Upgrade[];
  onPurchase: (upgradeId: string) => void;
}