/**
 * Represents a purchasable building or upgrade in the game.
 */
export interface Upgrade {
    id: string;
    name: string;
    description: string;
    baseCost: number;
    baseCps: number; // Cookies Per Second generated by one instance of this upgrade
    icon: string; // Emoji or image URL representing the upgrade
}

/**
 * Represents the current state of the player's game.
 * This is the object that will be serialized and saved to localStorage.
 */
export interface GameState {
    cookies: number; // Current available currency
    totalCookies: number; // Lifetime cookies earned (useful for achievements/prestige later)
    clickPower: number; // How many cookies are generated per manual click
    upgrades: Record<string, number>; // Dictionary mapping Upgrade ID to quantity owned
    lastSaveTime: number; // Unix timestamp of the last save
    startTime: number; // Unix timestamp of when the run started
}

/**
 * Configuration constants for the game engine.
 */
export interface GameConfig {
    tickRateMs: number; // How often the game loop runs (e.g., 100ms for 10 ticks/sec)
    autoSaveIntervalMs: number; // How often to automatically save to localStorage
    costMultiplier: number; // The multiplier applied to an upgrade's cost for each one owned (typically 1.15)
}

/**
 * Represents a floating text animation spawned by clicking.
 */
export interface FloatingText {
    id: string;
    x: number;
    y: number;
    value: number;
    timestamp: number;
}

/**
 * Standard interface for UI components that need to render and update based on game state.
 */
export interface GameComponent {
    /**
     * Mounts the component to the provided DOM element.
     */
    render(container: HTMLElement): void;
    
    /**
     * Updates the component's DOM based on the latest game state.
     * Should be called by the main game loop.
     */
    update?(state: GameState, currentCps: number): void;
}