import { GameState, Upgrade } from './types';

/**
 * Formatter for large numbers (e.g., 1.2M, 3.4B)
 */
const compactFormatter = new Intl.NumberFormat('en-US', {
    notation: "compact",
    compactDisplay: "short",
    maximumFractionDigits: 2
});

/**
 * Formats a number for display in the UI.
 * Numbers under 10,000 are shown with commas (e.g., 9,999).
 * Numbers 10,000 and above are compacted (e.g., 10K, 1.2M).
 * 
 * @param num The number to format
 * @returns A formatted string representation of the number
 */
export function formatNumber(num: number): string {
    if (num < 10000) {
        return Math.floor(num).toLocaleString('en-US');
    }
    return compactFormatter.format(num);
}

/**
 * Calculates the cost of the next upgrade based on how many are currently owned.
 * Formula: BaseCost * (Multiplier ^ Owned)
 * 
 * @param baseCost The initial cost of the upgrade
 * @param quantityOwned How many of this upgrade the player currently owns
 * @param multiplier The cost scaling factor (default is typically 1.15)
 * @returns The calculated cost for the next purchase
 */
export function calculateUpgradeCost(baseCost: number, quantityOwned: number, multiplier: number = 1.15): number {
    return Math.ceil(baseCost * Math.pow(multiplier, quantityOwned));
}

/**
 * Calculates the total Cookies Per Second (CPS) generated by all owned upgrades.
 * 
 * @param ownedUpgrades A dictionary mapping upgrade IDs to quantities owned
 * @param availableUpgrades The master list of all upgrade definitions
 * @returns The total CPS
 */
export function calculateTotalCps(ownedUpgrades: Record<string, number>, availableUpgrades: Upgrade[]): number {
    let totalCps = 0;
    
    for (const upgrade of availableUpgrades) {
        const owned = ownedUpgrades[upgrade.id] || 0;
        totalCps += owned * upgrade.baseCps;
    }
    
    return totalCps;
}

/**
 * The key used to store the game state in localStorage.
 */
export const SAVE_KEY = 'cookie_clicker_save_v1';

/**
 * Serializes and saves the current game state to localStorage.
 * Updates the lastSaveTime before saving.
 * 
 * @param state The current game state to save
 */
export function saveGame(state: GameState): void {
    try {
        const stateToSave: GameState = {
            ...state,
            lastSaveTime: Date.now()
        };
        localStorage.setItem(SAVE_KEY, JSON.stringify(stateToSave));
    } catch (error) {
        console.error("Failed to save game to localStorage:", error);
    }
}

/**
 * Attempts to load and deserialize the game state from localStorage.
 * 
 * @returns The loaded GameState, or null if no save exists or loading fails
 */
export function loadGame(): GameState | null {
    try {
        const savedData = localStorage.getItem(SAVE_KEY);
        if (!savedData) {
            return null;
        }
        
        const parsedState = JSON.parse(savedData) as GameState;
        
        // Basic validation to ensure the loaded state has the required shape
        if (typeof parsedState.cookies !== 'number' || typeof parsedState.upgrades !== 'object') {
            console.warn("Corrupted save data detected. Starting fresh.");
            return null;
        }
        
        return parsedState;
    } catch (error) {
        console.error("Failed to load game from localStorage:", error);
        return null;
    }
}

/**
 * Clears the saved game state from localStorage.
 */
export function clearSave(): void {
    try {
        localStorage.removeItem(SAVE_KEY);
    } catch (error) {
        console.error("Failed to clear save from localStorage:", error);
    }
}

/**
 * Creates a fresh, initial game state for new players or hard resets.
 * 
 * @returns A new GameState object
 */
export function createInitialGameState(): GameState {
    const now = Date.now();
    return {
        cookies: 0,
        totalCookies: 0,
        clickPower: 1,
        upgrades: {},
        lastSaveTime: now,
        startTime: now
    };
}